#!/bin/bash
 if [ "$#" -eq  "0" ]
   then
   	echo "Introduzca el nombre del archivo a revisar por el lexer:"
   	read var1
   	clear
   	python3 lexer.py $var1

 else
 	clear
 	python3 lexer.py $1
 fi


